BINANCE_API_KEY = "PASTE_NEW_BINANCE_API_KEY_HERE"
BINANCE_API_SECRET = "PASTE_NEW_BINANCE_API_SECRET_HERE"

TELEGRAM_BOT_TOKEN = "PASTE_NEW_TELEGRAM_BOT_TOKEN_HERE"
TELEGRAM_CHAT_ID = "@GlobalSignalHub1"

SYMBOLS = ["RUNEUSDT", "BTCUSDT", "ETHUSDT", "BNBUSDT"]

FUTURE_TYPE = "USDT"
INTERVAL = "1h"
CANDLE_LIMIT = 250

RISK_PERCENT = 3.0

# Use only one leverage per signal to avoid duplicate signals
LEVERAGE_LEVELS = [10]

TARGET_MULTIPLIERS = {
    "scalping": [0.75, 1.5, 2.5],
    "day": [3.5, 5.0, 6.5],
    "swing": [8.5, 10.5],
}

MAX_SIGNALS_PER_DAY = 2

MORNING_SIGNAL_WINDOW = ("06:00", "10:00")
EVENING_SIGNAL_WINDOW = ("16:00", "20:00")

STATE_FILE = "signal_state.json"
MANUAL_OVERRIDE_FLAG = "--manual"

OPEN_TRADES_FILE = "open_trades.json"
CLOSED_TRADES_FILE = "closed_trades.json"